
[general]
enabled = true

[colors]
unexplored = "#050810F2"
explored = "#17202B9E"

[vision]
unit_radius = 56.0
building_radius = 56.0
soft_edge = 4.0
update_interval = 0.12

[tower_vision]
wall_radius = 5.0
tower1_radius = 65.0
tower2_radius = 57.0
tower3_radius = 58.0
tower4_radius = 60.0
tower5_radius = 60.0

[civilian_vision]
radius = 10.0

[lord_base_vision]
radius = 85.0

[minimap]
fog_updates_per_second = 3.33
